name: Lint, Build and Test

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn test
      - uses: codecov/codecov-action@v1
        with:
          files: ./packages/inline_blocks/coverage/lcov.info
          flags: inline_blocks
          name: "@nishans/inline-blocks"
      - uses: codecov/codecov-action@v1
      - uses: codecov/codecov-action@v1
        with:
          files: ./packages/core/coverage/lcov.info
          flags: core
          name: "@nishans/core"
      - uses: codecov/codecov-action@v1
        with:
          files: ./packages/notion-formula/coverage/lcov.info
          flags: notion_formula
          name: "@nishans/notion-formula"
      - uses: codecov/codecov-action@v1
        with:
          files: ./packages/endpoints/coverage/lcov.info
          flags: endpoints
          name: "@nishans/endpoints"
      - uses: codecov/codecov-action@v1
        with:
          files: ./packages/cache/coverage/lcov.info
          flags: cache
          name: "@nishans/cache"
      - uses: codecov/codecov-action@v1
        with:
          files: ./packages/operations/coverage/lcov.info
          flags: operations
          name: "@nishans/operations"
      - uses: codecov/codecov-action@v1
        with:
          files: ./packages/idz/coverage/lcov.info
          flags: idz
          name: "@nishans/idz"
      - uses: codecov/codecov-action@v1
        with:
          files: ./packages/errors/coverage/lcov.info
          flags: errors
          name: "@nishans/errors"
